version: '3'
services:
  cfboom-util:
    build:
      context: .
      args:
        RUN_TESTS: "false"
    image: cfboom/util
    container_name: cfboom-util
    ports:
    - "8888:8888"
    volumes:
    - .:/var/www/modules/cfboom/modules/cfboom-util
